---
collections:
  - name: ansible.scm
  - name: community.general
  - name: ansible.platform
  - name: infra.aap_configuration
  - name: infra.ee_utilities
  - name: ansible.controller
  - name: containers.podman
